spring.application.name=gateway
server.port=5003
server.servlet.context-path = /
#DB_CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


#Redis_config
spring.cache.type=redis
spring.data.redis.host=redis-server
spring.data.redis.port=6379

eureka.client.service-url.defaultZone= http://serviceregistory:5004/eureka/
eureka.instance.prefer-ip-address=true

#app_config
payment.session.timeout=30;

management.endpoints.web.exposure.include=health,info
eureka.instance.health-check-url-path=${server.servlet.context-path}/actuator/health
eureka.instance.status-page-url-path=${server.servlet.context-path}/actuator/info