apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: payment-orch
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: pratham12102001/gateway:v1-0606261231
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        ports:
        - containerPort: 5003
        env:
        - name: AES_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: orch-secrets
              key: AES_SECRET_KEY
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: orch-secrets
              key: DB_PASS 
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: orch-secrets
              key: DB_URL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: orch-secrets
              key: DB_USER 
        - name: SECRET_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: orch-secrets
              key: SECRET_ENCRYPTION_KEY  


---

apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: payment-orch
spec:
  selector:
    app: gateway
  ports:
  - port: 5003
    targetPort: 5003
