spring.application.name=router

    server.servlet.context-path=/orbyte/router/api/v1
server.port=5005

app.environment=dev

#DB_CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


#Redis_config
spring.cache.type=redis
spring.data.redis.host=redis-server
spring.data.redis.port=6379

#euraka
eureka.client.service-url.defaultZone= http://serviceregistory:5004/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
eureka.instance.health-check-url-path=${server.servlet.context-path}/actuator/health
eureka.instance.status-page-url-path=${server.servlet.context-path}/actuator/info