spring:
  application:
    name: tokenizer

  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  cache:
    type: redis

  data:
    redis:
      host: redis-server
      port: 6379

server:
  servlet:
    context-path: /orbyte/tokenizer/api/v1
  port: 5002

app:
  environment: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistory:5004/eureka/

  instance:
    health-check-url-path: ${server.servlet.context-path}/manage/health
    prefer-ip-address: true

encryption:
  aes:
    secret-key: ${AES_SECRET_KEY} # generate your key using --- api
    key-algorithm: AES
    cipher-algorithm: AES/GCM/NoPadding
    tag-length-bits: 128
    iv-length-bytes: 12

orbyte:
  secret: ${SECRET_ENCRYPTION_KEY}

debug: true
