spring.application.name=tokenizer


server.servlet.context-path=/orbyte/tokenizer/api/v1
app.environment=${ENVIRONMENT}

#debug=true
server.port=5002

#DB_CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/orbit
spring.datasource.username=admin
spring.datasource.password=mypassword

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


#Redis_config
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379