spring.application.name=serviceregistory

server.port=5004
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Prevents split-brain warnings in single node setup
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Stops the unavailable-replicas warning you saw earlier
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:5004/eureka/
