-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.audit_detail_id_seq;

CREATE SEQUENCE public.audit_detail_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.audit_detail_id_seq OWNER TO "admin";
GRANT ALL ON SEQUENCE public.audit_detail_id_seq TO "admin";

-- DROP SEQUENCE public.bin_lookup_id_seq;

CREATE SEQUENCE public.bin_lookup_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.bin_lookup_id_seq OWNER TO "admin";
GRANT ALL ON SEQUENCE public.bin_lookup_id_seq TO "admin";

-- DROP SEQUENCE public.config_config_id_seq;

CREATE SEQUENCE public.config_config_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.config_config_id_seq OWNER TO "admin";
GRANT ALL ON SEQUENCE public.config_config_id_seq TO "admin";

-- DROP SEQUENCE public.orb_token_tid_seq;

CREATE SEQUENCE public.orb_token_tid_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.orb_token_tid_seq OWNER TO "admin";
GRANT ALL ON SEQUENCE public.orb_token_tid_seq TO "admin";

-- DROP SEQUENCE public.routing_rules_id_seq;

CREATE SEQUENCE public.routing_rules_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.routing_rules_id_seq OWNER TO "admin";
GRANT ALL ON SEQUENCE public.routing_rules_id_seq TO "admin";

-- DROP SEQUENCE public.user_detail_seq;

CREATE SEQUENCE public.user_detail_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.user_detail_seq OWNER TO "admin";
GRANT ALL ON SEQUENCE public.user_detail_seq TO "admin";
-- public.audit_detail definition

-- Drop table

-- DROP TABLE public.audit_detail;

CREATE TABLE public.audit_detail ( id bigserial NOT NULL, txn_id uuid NOT NULL, processor varchar(100) NOT NULL, "method" varchar(100) NOT NULL, "type" varchar NOT NULL, "data" jsonb NOT NULL, created_on timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT audit_detail_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE public.audit_detail OWNER TO "admin";
GRANT ALL ON TABLE public.audit_detail TO "admin";


-- public.bin_lookup definition

-- Drop table

-- DROP TABLE public.bin_lookup;

CREATE TABLE public.bin_lookup ( id bigserial NOT NULL, bin varchar(20) NOT NULL, "data" jsonb NOT NULL, created_on timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT bin_lookup_pkey PRIMARY KEY (id), CONSTRAINT bin_lookup_unique UNIQUE (bin));

-- Permissions

ALTER TABLE public.bin_lookup OWNER TO "admin";
GRANT ALL ON TABLE public.bin_lookup TO "admin";


-- public.config definition

-- Drop table

-- DROP TABLE public.config;

CREATE TABLE public.config ( config_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "owner" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, value varchar(255) NULL, updated_on timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, modified_by varchar(255) NOT NULL, CONSTRAINT config_pkey PRIMARY KEY (config_id), CONSTRAINT unique_owner_name UNIQUE (owner, name));
CREATE INDEX idx_config_owner_name ON public.config USING btree (owner, name);

-- Permissions

ALTER TABLE public.config OWNER TO "admin";
GRANT ALL ON TABLE public.config TO "admin";


-- public.failover_txn definition

-- Drop table

-- DROP TABLE public.failover_txn;

CREATE TABLE public.failover_txn ( failed_txn_id uuid DEFAULT uuidv7() NOT NULL, status varchar(100) NOT NULL, sub_status varchar(100) NOT NULL, processor varchar(100) NULL, proc_txn_id varchar(255) NULL, proc_txn_status varchar(100) NULL, payment_method varchar(100) NOT NULL, amount int4 NOT NULL, currency bpchar(3) NOT NULL, created_on timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_on timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT failover_txn_pkey PRIMARY KEY (failed_txn_id));

-- Permissions

ALTER TABLE public.failover_txn OWNER TO "admin";
GRANT ALL ON TABLE public.failover_txn TO "admin";


-- public.orb_token definition

-- Drop table

-- DROP TABLE public.orb_token;

CREATE TABLE public.orb_token ( tid int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, card_payload jsonb NULL, created numeric(38) NOT NULL, created_on timestamp(6) NOT NULL, modified_by varchar(255) NOT NULL, provider varchar(255) NOT NULL, token_id varchar(255) NOT NULL, "type" int2 NOT NULL, used bool NOT NULL, CONSTRAINT orb_token_modified_by_check CHECK (((modified_by)::text = ANY ((ARRAY['ORCHESTRATOR'::character varying, 'SYSTEM'::character varying, 'MANUAL'::character varying, 'TOKENIZER'::character varying])::text[]))), CONSTRAINT orb_token_pkey PRIMARY KEY (tid), CONSTRAINT orb_token_type_check CHECK (((type >= 0) AND (type <= 1))));

-- Permissions

ALTER TABLE public.orb_token OWNER TO "admin";
GRANT ALL ON TABLE public.orb_token TO "admin";


-- public.routing_rules definition

-- Drop table

-- DROP TABLE public.routing_rules;

CREATE TABLE public.routing_rules ( id bigserial NOT NULL, "name" varchar(100) NOT NULL, priority int4 NOT NULL, currency varchar(10) NULL, card_type varchar(20) NULL, country varchar(10) NULL, merchant_category varchar(50) NULL, amount_min numeric(18, 2) NULL, amount_max numeric(18, 2) NULL, is_recurring bool NULL, channel varchar(20) NULL, payment_method varchar(20) NULL, bin_brand varchar(20) NULL, extra_expression text NULL, processor varchar(50) NOT NULL, fallback_processors varchar(200) NULL, active bool DEFAULT true NULL, created_at timestamp DEFAULT now() NULL, updated_at timestamp DEFAULT now() NULL, CONSTRAINT routing_rules_pkey PRIMARY KEY (id));
CREATE INDEX idx_routing_amount ON public.routing_rules USING btree (amount_min, amount_max) WHERE (active = true);
CREATE INDEX idx_routing_lookup ON public.routing_rules USING btree (currency, card_type, country, priority) WHERE (active = true);
CREATE INDEX idx_routing_wildcards ON public.routing_rules USING btree (priority) WHERE ((active = true) AND (currency IS NULL) AND (card_type IS NULL));

-- Permissions

ALTER TABLE public.routing_rules OWNER TO "admin";
GRANT ALL ON TABLE public.routing_rules TO "admin";


-- public.txn definition

-- Drop table

-- DROP TABLE public.txn;

CREATE TABLE public.txn ( txn_id uuid DEFAULT uuidv7() NOT NULL, status varchar(100) NOT NULL, sub_status varchar(100) NOT NULL, processor varchar(100) NULL, proc_txn_id varchar(255) NULL, proc_txn_status varchar(100) NULL, payment_method varchar(100) NULL, amount int8 NOT NULL, currency bpchar(3) NOT NULL, created_on timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_on timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, description text NULL, txn_date timestamp NULL, is_failed_first bool DEFAULT false NULL, CONSTRAINT txn_pkey PRIMARY KEY (txn_id));

-- Permissions

ALTER TABLE public.txn OWNER TO "admin";
GRANT ALL ON TABLE public.txn TO "admin";


-- public."session" definition

-- Drop table

-- DROP TABLE public."session";

CREATE TABLE public."session" ( session_id varchar(255) NOT NULL, amount int4 NOT NULL, currency bpchar(3) NOT NULL, created_on timestamp DEFAULT CURRENT_TIMESTAMP NULL, txn_id uuid NULL, CONSTRAINT session_pkey PRIMARY KEY (session_id), CONSTRAINT fk_session_txn FOREIGN KEY (txn_id) REFERENCES public.txn(txn_id) ON DELETE CASCADE);

-- Permissions

ALTER TABLE public."session" OWNER TO "admin";
GRANT ALL ON TABLE public."session" TO "admin";




-- Permissions

GRANT ALL ON SCHEMA public TO pg_database_owner;
GRANT USAGE ON SCHEMA public TO public;